version: "3"

services:
  common: &common
    image: fdb-document-layer-build:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    networks: [test-net]

  fdbserver:
    image: fdb-standalone:0.0.2
    build:
      context: fdbserver
      args:
        - FDB_VERSION=6.0.15
    environment:
      - FDB_PORT=4500

  build-setup: &build-setup
    <<: *common
    depends_on: [common]
    volumes:
      - ..:/fdb-document-layer
    working_dir: /fdb-document-layer

  build-release: &build-release
    <<: *build-setup
    environment:
      - MAKEJOBS=1
      - RELEASE=1
    command: bash -cl 'mkdir -p build && cd build && cmake .. && make -j "$${MAKEJOBS}" package'

  build-snapshot: &build-snapshot
    <<: *build-setup
    environment:
      - MAKEJOBS=1
    command: bash -cl 'mkdir -p build && cd build && cmake .. && make -j "$${MAKEJOBS}" package'

  build-prb:
    <<: *build-snapshot

  test-snapshot: &test-snapshot
    <<: *build-setup
    environment:
      - MAKEJOBS=1
      - FDB_HOST=fdbserver
      - FDB_PORT=4500
    command: bash -cl 'mkdir -p build && cd build && cmake .. && make -j "$${MAKEJOBS}" && cd .. && bash run-tests.bash'
    links:
      - fdbserver
    depends_on:
      - fdbserver

  test-prb:
    <<: *test-snapshot
    environment:
      - MAKEJOBS=1
      - FDB_HOST=fdbserver
      - FDB_PORT=4500

  shell:
    <<: *build-setup
    volumes:
      - ..:/fdb-document-layer
    entrypoint: /bin/bash
    links:
      - fdbserver
    depends_on:
      - fdbserver

networks:
  test-net:
